### ISSUE TITLE
v2rayN?

### ISSUE THREAD

**Issue by c2ray** [felix-fly/v2ray-adlist#1]
请问v2rayN该如何加载site.dat?
我把文件放置在v2rayN目录下, 但是site.dat 并没有被加载
![image](https://user-images.githubusercontent.com/55729509/148077152-bb8bd45d-d180-4b44-93e6-e155192a6485.png)
![image](https://user-images.githubusercontent.com/55729509/148077311-61d1b0d8-2954-4d83-ad7d-b9192290eef1.png)

**Comment by felix-fly** [comment]
目测应该可以修改 `guiNConfig.json` 文件

```
"routing": {
    "strategy": "rules",
    "settings": {
      "rules": [{
        "type": "field",
        "domain" : ["ext:site.dat:gw"],
        "outboundTag": "proxy"
      }, {
        "type": "field",
        "domain" : ["ext:site.dat:ad"],
        "outboundTag": "blocked"
      }]
    }
  }
```
